language: ruby
cache:
- bundler
before_install:
- gem install bundler -v 2.0
install:
- bundle install
rvm:
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    - rich.m.chatterton@gmail.com
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-windows.gemspec
- gem install sensu-plugins-windows-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: ikQPH10uf07ZuXs64PDeg0wMKMiuINiJiYzncdfe77iI0FFE13kcFYv8T2HxaeXjJPRXkiNkBprld2EG7Sm1Dd7WYKVByW55fIfd96wZe+a/ObPflbHbVb1fbwd5A0kK7BuHgrV1AKb++Nq9LEDJPiPJTgktaM8thJqYkjwDegg=
  gem: sensu-plugins-windows
  on:
    tags: true
    all_branches: true
    rvm: 2.3.0
    rvm: 2.4.1
    repo: sensu-plugins/sensu-plugins-windows
